export default {
  // Router

  LOCATION_CHANGE_HANDLE: "LOCATION_CHANGE_HANDLE",
  LOCATION_CHANGE_HANDLE_CONTENT_FETCH: "LOCATION_CHANGE_HANDLE_CONTENT_FETCH",
  LOCATION_CHANGE_HANDLE_BOARD_FETCH: "LOCATION_CHANGE_HANDLE_BOARD_FETCH",
};
